name: perf-criterion
version: '0.0.0.1'
synopsis: See readme.md
description: See readme.md for description.
category: project
author: Tony Day
maintainer: tonyday567@gmail.com
copyright: Tony Day (c) 2017
license: BSD3
github: tonyday567/perf-criterion
extra-source-files:
  - readme.md
  - stack.yaml
default-extensions:
  - NegativeLiterals
  - NoImplicitPrelude
  - OverloadedStrings
  - UnicodeSyntax
dependencies:
  - base >=4.7 && <5

library:
  source-dirs: src
  exposed-modules:
    - Perf.Criterion
  dependencies:
    - base >=4.7 && <4.12
    - containers
    - criterion
    - criterion-measurement
    - deepseq
    - text
    - formatting
    - scientific
    - perf
    - perf-analysis

executables:
  perf-criterion:
    main: perf-criterion.lhs
    source-dirs: app
    ghc-options:
      - -funbox-strict-fields
      - -fforce-recomp
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - protolude
      - optparse-generic
      - perf
      - perf-analysis
      - criterion
      - criterion-measurement
      - deepseq
      - perf-criterion
      - text
      - formatting
      - scientific
