language: generic

cache:
  directories:
  - $HOME/.stack
  - $TRAVIS_BUILD_DIR/.stack-work

matrix:
  include:
    - env: BUILD=stack
      # a -Werror build that is allowed to fail
    - env: BUILD=werror

  allow_failures:
    - env: BUILD=werror

install:
- |
      PATH=$HOME/.local/bin:$PATH
      mkdir -p ~/.local/bin
      travis_retry curl -L https://get.haskellstack.org/stable/linux-x86_64.tar.gz | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'

script:
- |
  case "$BUILD" in
    stack)
      stack --no-terminal $ARGS test --haddock --no-haddock-deps
      ;;
    werror)
      stack --no-terminal $ARGS test --haddock --no-haddock-deps --ghc-options -Werror --ghc-options -Wcompat --ghc-options -Wincomplete-record-updates --ghc-options -Wincomplete-uni-patterns --ghc-options -Wredundant-constraints
      ;;
  esac
