name: perf
version: '0.3.1.0'
synopsis: low-level performance statistics
description: ! '

  A set of tools to measure time performance.

'
category: project
author: Tony Day
maintainer: tonyday567@gmail.com
copyright: Tony Day
license: BSD3
github: tonyday567/perf
extra-source-files:
- stack.yaml
default-extensions:
- NegativeLiterals
- NoImplicitPrelude
- OverloadedStrings
- UnicodeSyntax
dependencies:
- protolude
library:
  source-dirs: src
  default-extensions:
  - BangPatterns
  - TypeSynonymInstances
  exposed-modules:
  - Perf
  - Perf.Measure
  - Perf.Cycle
  dependencies:
  - base >=4.7 && <4.11
  - containers
  - foldl
  - numhask >=0.1.2 && <0.2
  - rdtsc
  - tdigest
  - time
executables:
  perf-examples:
    main: examples.hs
    source-dirs: examples
    default-extensions:
    - ScopedTypeVariables
    ghc-options:
    - -fforce-recomp
    - -rtsopts
    - -O2
    dependencies:
    - base >=4.7 && <4.11
    - formatting
    - numhask
    - optparse-generic
    - perf
    - scientific
    - text
    - vector
tests:
  test:
    main: test.hs
    source-dirs: test
    dependencies:
    - base >=4.7 && <5
    - doctest
    - perf
