#+TITLE: perf
#+PROPERTY: header-args :exports both
#+PROPERTY: header-args :eval no-export

* perf
:PROPERTIES:
:EXPORT_FILE_NAME: perf
:export_date: 2022-2-22
:END:

** intro

~perf~ provides some ideas, code and a library for low-level performance measurement for Haskell hacking. The library:

- provides a monad transformer, ~PerfT~, as a light-weight wrapper for use on existing code. ~PerfT~ modifications can be included in code bases, as opposed to performance being separated code and  process, with any effects able to be erased at compile time with ~evalPerfT~.

- focuses on using the rdtsc instruction set that comes with the x86 chip to measure accurate time performance as number of clock cycles.

- abstracts the concept of what is being measured, so that concepts such as counters, debug checks, time and space performance can be treated equivalently.

** Setup

Note that running this readme.org is very slow compared with an external process which accesses the compiled version of the library.

#+begin_src haskell :results output :exports both
:r
:set prompt " > "
:set -Wno-type-defaults
:set -Wno-name-shadowing
:set -XOverloadedStrings
import Perf
putStrLn "ok"
#+end_src

#+RESULTS:
: Ok, 8 modules loaded.
: >  >  >  >  > ok

** Time
*** What is a tick?

The fundamental operation of Perf.Time is tick, which sandwiches a (strict) function application between two readings of the rdstc chip.

#+begin_src haskell :results output :exports both
:t tick
#+end_src

#+RESULTS:
: tick :: (a -> b) -> a -> IO (Cycles, b)

tick returns in the IO monad, because reading a cycle counter is an IO effect. The trivial but fundamental point is that performance measurement effects the computation being measured.

Unlike benchmarking-style libraries, such as criterion, the result of the computation is passed through along with the cycle count. In this way, the `Perf` monad can be inserted into the midst of a computation in an attempt to measure performance in-situ as opposed to sitting off in a separate and perhaps unrepresentative process.

*** tick_

tick_ measures the number of cycles between two clock reads.

#+begin_src haskell :results output :exports both
:t tick_
#+end_src

#+RESULTS:
: tick_ :: IO Cycles

#+begin_src haskell :results output :exports both
import Control.Monad
replicateM 10 tick_
#+end_src

#+RESULTS:
| 10260 | 998 | 838 | 794 | 800 | 788 | 790 | 832 | 802 | 818 |

*** multiple ticks

#+begin_src haskell :results output :exports both
fmap (fmap fst) . replicateM 10 $ tick (const ()) ()
#+end_src

#+RESULTS:
| 8610 | 3654 | 2900 | 2932 | 2672 | 2708 | 2684 | 2664 | 2582 | 2652 |

Here, ~const () ()~ was evaluated and took 6.7k cycles for the first effect, reducing down to 2.2k after 10 effects. What it did in that time we will never know, really, at least from usage of ~perf~. 2.2k cycles is, on my 2.5GHz machine equal to 2200 / 2.5e9 = 8.8e-7 of a second or 880 nanoseconds.

*** tickIO

~tickIO~ measures the evaluation of an IO value.

#+begin_src haskell :results output :exports both
:t tickIO
#+end_src

#+RESULTS:
: tickIO :: IO a -> IO (Cycles, a)

#+begin_src haskell :results output :exports both
fmap (fmap fst) . replicateM 10 $ tickIO (pure ())
#+end_src

#+RESULTS:
| 5840 | 2602 | 1910 | 1698 | 1668 | 1660 | 1672 | 1676 | 1680 | 1662 |

#+begin_src haskell :results output :exports both
ticks 100 (const ()) ()
#+end_src

#+RESULTS:
| 8226 | 3298 | 3254 | 2686 | 2694 | 2724 | 2868 | 2732 | 2644 | 2678 | 2680 | 2896 | 2734 | 2606 | 2608 | 2598 | 2606 | 2738 | 2742 | 2610 | 2554 | 2532 | 2576 | 2592 | 2600 | 2562 | 2786 | 2592 | 2646 | 2624 | 2666 | 2640 | 2640 | 2602 | 2672 | 2560 | 3478 | 2556 | 2552 | 2572 | 2622 | 2492 | 2572 | 2706 | 2544 | 2604 | 2748 | 2570 | 2596 | 3078 | 2666 | 2592 | 2612 | 2648 | 2594 | 2564 | 2716 | 2564 | 2594 | 2596 | 2554 | 2766 | 2552 | 3026 | 2602 | 2860 | 2632 | 2614 | 2620 | 2586 | 3014 | 2626 | 2626 | 2614 | 2830 | 2624 | 2616 | 2648 | 2610 | 2626 | 2610 | 2590 | 2930 | 2622 | 2732 | 2698 | 3004 | 2664 | 2948 | 2630 | 2588 | 2766 | 2726 | 2600 | 2634 | 2792 | 2704 | 2774 | 2638 | 2634 |

*** sum example

#+begin_src haskell :results output :exports both
fmap (comma (Just 3) . fromIntegral) . fst <$> ticks 10 sum ([1..10000] :: [Double])
#+end_src

#+RESULTS:
| 3,680,000 | 5,020,000 | 726,000 | 693,000 | 2,880,000 | 746,000 | 671,000 | 1,730,000 | 626,000 | 618,000 |


#+begin_src haskell :results output :exports both
ts <- ticks 10000 sum ([1..1000] :: [Double])
putStrLn $ Text.unpack $ average (fst ts)
#+end_src

#+RESULTS:
: 58,800

** PerfT

~PerfT~ allows for multiple measurement points and is polymorphic in what is being measured. It returns a Map of results held in State.

Compare a lower-level usage of ticks, measuring the average of summing to one thousand over one thousand trials:

#+begin_src haskell :results output :exports both
averageD . fst <$> ticks 1000 sum [1..1000]
#+end_src

#+RESULTS:
: 69231.902

... with PerfT usage

#+begin_src haskell :results output :exports both
import qualified Data.Map.Strict as Map
fmap averageD <$> execPerfT (times 1000) (sum |$| [1..1000])
#+end_src

#+RESULTS:
: fromList [("",71529.594)]

Comparing performance of sum versus a list fusion approach:

#+begin_src haskell :results output :exports both
import qualified Data.Map.Strict as Map
:set -Wno-unused-do-bind
fmap averageD <$> (execPerfT (times 1000) $ do; (fap "sum" sum [1..1000]); (fap "fusion" (\x -> sum [1..x]) 1000))
#+end_src

#+RESULTS:
: > fromList [("fusion",118589.68),("sum",73765.894)]

An IO example

#+begin_src haskell :results output :exports both
exampleIO' :: IO ()
exampleIO' = do
  txt <- Text.readFile "src/Perf.hs"
  let n = Text.length txt
  Text.putStrLn $ "length of file is: " <> Text.pack (show n)
#+end_src

#+RESULTS:
: >  > length of file is: 1927

#+begin_src haskell :results output :exports both
import Data.Semigroup
exampleIO = execPerfT time (do
  txt <- fam "file read" (Text.readFile "src/Perf.hs")
  n <- fap "length" Text.length txt
  fam "print result" (Text.putStrLn $ "length of file is: " <> Text.pack (show n)))
#+end_src

#+begin_src sh :results drawer
perf-explore -r 10 -l 100000 --exampleIO +RTS -T -RTS
#+end_src

#+RESULTS:
:results:
length of file is: 1927
|label1|results|
|---|---|
|file read|4.37e5|
|length|4.75e3|
|print result|5.52e4|

outer version

length of file is: 1927
|label1|results|
|---|---|
|file read|1.01e5|
|length|4.51e3|
|print result|5.29e3|
|total|1.16e5|

slop version

length of file is: 1927
|label1|results|
|---|---|
|file read|9.16e4|
|length|4.43e3|
|print result|5.07e3|
|slop|1.35e3|
|total|1.02e5|
:end:

** perf-explore

~perf-explore~ contains some exploratory routines to help develop =perf=

#+begin_src sh :results output :exports both
perf-explore --help
#+end_src

#+RESULTS:
#+begin_example
basic perf callibration

Usage: perf-explore [-r|--runs ARG] [-l|--length ARG]
                    [--best | --median | --average | --averagesecs]
                    [--default | --sums | --noop | --ticks | --gauge | --space |
                      --spacetime] [-s|--sum ARG]
                    [--sumFuse | --sum | --lengthF | --constFuse | --mapInc]

  perf benchmarking

Available options:
  -r,--runs ARG            number of runs to perform
  -l,--length ARG          length of list
  --best                   report upper decile
  --median                 report median
  --average                report average
  --averagesecs            report average in seconds
  --default                default measurement (polySum)
  --sums                   sums
  --noop                   no-ops
  --ticks                  tick types
  --gauge                  gauge comparison
  --space                  space stats
  --spacetime              space and time stats
  -s,--sum ARG             type of sum code
  --sumFuse                fused sum pipeline
  --sum                    sum
  --lengthF                foldr id length
  --constFuse              fused const pipeline
  --mapInc                 fmap (+1)
  -h,--help                Show this help text
#+end_example

#+begin_src haskell :results output :exports both
import qualified Data.Map.Strict as Map
fmap averageD <$> execPerfT (times 10000) (sum |$| [1..1000])
#+end_src

#+RESULTS:
: fromList [("",59721.9976)]

The equivalent to the above code is:

#+begin_src sh :results drawer :exports both
perf-explore -r 10000 -l 1000 --sum
#+end_src

#+RESULTS:
:results:
| stat | result |
|------+--------|
| sum  | 8.80e3 |
:end:

*** noops

#+begin_src sh :results drawer :exports both
perf-explore --noop
#+end_src

#+RESULTS:
:results:
"other/RunNoOp.csv"
|label1|label2|results|
|---|---|---|
|average|fams|2.32e1|
|average|faps|2.43e1|
|best|fams|1.94e1|
|best|faps|1.94e1|
|first 10|fams|132.0 46.0 18.0 22.0 22.0 22.0 22.0 26.0 22.0 118.0|
|first 10|faps|792.0 16.0 20.0 20.0 18.0 20.0 22.0 22.0 22.0 24.0|
|median|fams|2.15e1|
|median|faps|2.18e1|
:end:

#+begin_src haskell :results output :exports both
:r
:set -XOverloadedLabels
import qualified Data.Text as Text
import qualified Data.Map.Strict as Map
import Chart
import Prelude
import Optics.Core
m <- read <$> readFile "other/noop.map" :: IO (Map.Map Text.Text [Cycles])
let (Just d) = Map.lookup "fap times" m
filter (> 100) d
#+end_src

#+RESULTS:
| Cycles | (word = 792) | Cycles | (word = 258) |

#+begin_src haskell :file other/noop.svg :results output graphics file :exports both
writeChartSvg "other/noop.svg" $ mempty & #hudOptions .~ colourHudOptions (rgb light) defaultHudOptions & #charts .~ unnamed [(RectChart (defaultRectStyle & #borderSize .~ 0 & #color .~ Colour 1 1 1 1) (zipWith (\y x -> Rect x (x+1) 0 y) (fromIntegral <$> filter (<= 100) d) [0..]))]
#+end_src

#+RESULTS:
[[file:other/noop.svg]]

*** measurement context

Exploration of how the code surrounding measurement effects performance.

#+begin_src sh :results drawer
perf-explore -r 1000 -l 1000 --ticks
#+end_src

#+RESULTS:
:results:
|               | stepTime |   tick | tickForce | tickForceArgs | tickLazy | tickWHNF |  times |
| sumAux        |   2.54e4 | 1.89e4 |    3.36e4 |        2.90e4 |   1.90e1 |   1.70e4 | 2.86e4 |
| sumCata       |   2.10e4 | 2.34e4 |    1.98e4 |        2.00e4 |   1.88e1 |   1.96e4 | 1.91e4 |
| sumCo         |   1.86e4 | 2.58e4 |    1.84e4 |        1.85e4 |   1.91e1 |   1.89e4 | 1.92e4 |
| sumCoCase     |   1.82e4 | 2.03e4 |    1.82e4 |        1.65e4 |   1.95e1 |   1.64e4 | 1.83e4 |
| sumCoGo       |   2.01e4 | 2.20e4 |    2.24e4 |        1.85e4 |   1.89e1 |   2.33e4 | 1.86e4 |
| sumF          |   1.14e4 | 1.07e4 |    1.41e4 |        1.15e4 |   2.00e1 |   1.10e4 | 1.26e4 |
| sumFlip       |   1.26e4 | 1.08e4 |    1.39e4 |        1.15e4 |   2.08e1 |   1.29e4 | 1.29e4 |
| sumFlipLazy   |   1.40e4 | 1.22e4 |    1.28e4 |        1.10e4 |   1.91e1 |   1.06e4 | 1.66e4 |
| sumFoldr      |   2.10e4 | 1.99e4 |    2.22e4 |        1.94e4 |   1.87e1 |   2.06e4 | 1.93e4 |
| sumFuse       |   1.35e3 | 1.64e3 |    1.59e3 |        1.35e3 |   1.63e1 |   2.81e3 | 1.35e3 |
| sumFuseFoldl' |   1.35e3 | 1.35e3 |    1.35e3 |        1.35e3 |   1.75e1 |   1.35e3 | 1.35e3 |
| sumFuseFoldr  |   1.15e4 | 1.09e4 |    8.89e3 |        8.71e3 |   1.72e1 |   9.40e3 | 1.04e4 |
| sumFusePoly   |   1.97e3 | 2.01e3 |    1.97e3 |        2.01e3 |   1.65e1 |   1.97e3 | 2.50e3 |
| sumLambda     |   1.14e4 | 1.11e4 |    1.33e4 |        1.13e4 |   2.04e1 |   1.22e4 | 1.13e4 |
| sumMono       |   1.11e4 | 1.17e4 |    1.37e4 |        1.26e4 |   1.88e1 |   1.12e4 | 1.30e4 |
| sumPoly       |   1.14e4 | 1.17e4 |    1.43e4 |        1.27e4 |   1.99e1 |   1.15e4 | 1.96e4 |
| sumSum        |   1.21e4 | 1.32e4 |    1.50e4 |        1.35e4 |   1.92e1 |   1.11e4 | 1.27e4 |
| sumTail       |   1.03e4 | 1.12e4 |    1.26e4 |        1.06e4 |   2.03e1 |   1.20e4 | 1.19e4 |
| sumTailLazy   |   1.22e4 | 1.14e4 |    1.43e4 |        1.28e4 |   1.97e1 |   1.10e4 | 1.25e4 |
:end:


#+begin_src sh :results drawer
perf-explore -r 100000 -l 1000 --ticks
#+end_src

#+RESULTS:
:results:
|               | stepTime |   tick | tickForce | tickForceArgs | tickLazy | tickWHNF |  times |
| sumAux        |   1.90e4 | 1.89e4 |    1.91e4 |        1.91e4 |   1.91e1 |   1.91e4 | 1.90e4 |
| sumCata       |   2.04e4 | 2.02e4 |    2.05e4 |        2.03e4 |   1.91e1 |   2.03e4 | 2.03e4 |
| sumCo         |   1.86e4 | 1.87e4 |    1.88e4 |        1.86e4 |   1.91e1 |   1.87e4 | 1.86e4 |
| sumCoCase     |   1.58e4 | 1.83e4 |    1.64e4 |        1.59e4 |   1.94e1 |   1.83e4 | 1.59e4 |
| sumCoGo       |   2.06e4 | 2.06e4 |    2.07e4 |        2.06e4 |   1.91e1 |   2.06e4 | 2.07e4 |
| sumF          |   1.03e4 | 9.30e3 |    8.77e3 |        9.39e3 |   1.99e1 |   8.65e3 | 1.10e4 |
| sumFlip       |   8.61e3 | 8.49e3 |    8.39e3 |        8.44e3 |   1.91e1 |   8.42e3 | 8.73e3 |
| sumFlipLazy   |   1.19e4 | 8.73e3 |    8.41e3 |        2.11e4 |   1.91e1 |   8.43e3 | 1.19e4 |
| sumFoldr      |   2.08e4 | 2.11e4 |    2.06e4 |        2.07e4 |   1.90e1 |   2.06e4 | 2.06e4 |
| sumFuse       |   1.38e3 | 2.09e3 |    1.47e3 |        1.37e3 |   1.70e1 |   1.43e3 | 1.44e3 |
| sumFuseFoldl' |   1.39e3 | 1.59e3 |    1.40e3 |        1.59e3 |   1.79e1 |   1.41e3 | 1.39e3 |
| sumFuseFoldr  |   1.56e4 | 1.23e4 |    1.21e4 |        1.41e4 |   1.69e1 |   1.13e4 | 1.33e4 |
| sumFusePoly   |   2.40e3 | 2.61e3 |    2.24e3 |        2.05e3 |   1.97e1 |   2.25e3 | 2.39e3 |
| sumLambda     |   9.03e3 | 9.29e3 |    8.84e3 |        8.88e3 |   1.95e1 |   8.71e3 | 9.27e3 |
| sumMono       |   5.69e3 | 6.00e3 |    6.26e3 |        5.87e3 |   2.14e1 |   5.95e3 | 5.71e3 |
| sumPoly       |   8.98e3 | 8.90e3 |    9.00e3 |        8.78e3 |   1.93e1 |   8.98e3 | 8.95e3 |
| sumSum        |   7.95e3 | 8.47e3 |    8.02e3 |        7.97e3 |   1.92e1 |   8.02e3 | 7.93e3 |
| sumTail       |   5.98e3 | 7.16e3 |    6.01e3 |        5.87e3 |   1.91e1 |   8.01e3 | 6.10e3 |
| sumTailLazy   |   5.93e3 | 8.49e3 |    5.77e3 |        5.81e3 |   1.91e1 |   5.76e3 | 5.95e3 |
:end:

**** short list
#+begin_src sh :results drawer :exports both
perf-explore -r 10000 -l 10 --best --ticks
#+end_src

#+RESULTS:
:results:
|               | stepTime |   tick | tickForce | tickForceArgs | tickLazy | tickWHNF |  times |
| sumAux        |   9.14e1 | 9.53e1 |    9.42e1 |        9.17e1 |   1.71e1 |   9.25e1 | 9.27e1 |
| sumCata       |   8.81e1 | 9.05e1 |    8.97e1 |        8.95e1 |   1.71e1 |   8.80e1 | 8.91e1 |
| sumCo         |   9.30e1 | 9.58e1 |    9.44e1 |        9.40e1 |   1.69e1 |   9.13e1 | 9.15e1 |
| sumCoCase     |   9.31e1 | 9.56e1 |    9.43e1 |        9.46e1 |   1.71e1 |   9.20e1 | 9.22e1 |
| sumCoGo       |   8.88e1 | 9.11e1 |    8.92e1 |        8.96e1 |   1.71e1 |   8.75e1 | 8.93e1 |
| sumF          |   6.33e1 | 6.53e1 |    6.64e1 |        6.58e1 |   1.71e1 |   6.45e1 | 6.44e1 |
| sumFlip       |   6.41e1 | 6.93e1 |    6.58e1 |        6.56e1 |   1.73e1 |   6.52e1 | 6.35e1 |
| sumFlipLazy   |   6.44e1 | 6.63e1 |    6.55e1 |        6.58e1 |   1.68e1 |   6.38e1 | 6.36e1 |
| sumFoldr      |   8.83e1 | 9.16e1 |    8.94e1 |        8.92e1 |   1.71e1 |   8.82e1 | 8.91e1 |
| sumFuse       |   2.52e1 | 2.58e1 |    2.59e1 |        2.44e1 |   1.53e1 |   2.55e1 | 2.54e1 |
| sumFuseFoldl' |   2.53e1 | 2.52e1 |    2.57e1 |        2.49e1 |   1.47e1 |   2.37e1 | 2.52e1 |
| sumFuseFoldr  |   4.54e1 | 4.69e1 |    4.66e1 |        4.15e1 |   1.50e1 |   4.74e1 | 4.91e1 |
| sumFusePoly   |   5.06e1 | 5.01e1 |    5.10e1 |        4.91e1 |   1.50e1 |   4.92e1 | 5.02e1 |
| sumLambda     |   8.55e1 | 8.70e1 |    8.64e1 |        8.65e1 |   1.72e1 |   8.74e1 | 8.31e1 |
| sumMono       |   7.12e1 | 7.19e1 |    7.14e1 |        7.12e1 |   1.70e1 |   6.95e1 | 7.03e1 |
| sumPoly       |   8.54e1 | 8.71e1 |    8.61e1 |        8.67e1 |   1.71e1 |   8.42e1 | 8.35e1 |
| sumSum        |   8.55e1 | 8.55e1 |    8.79e1 |        8.60e1 |   1.66e1 |   8.42e1 | 8.33e1 |
| sumTail       |   7.36e1 | 9.00e1 |    7.91e1 |        7.56e1 |   1.93e1 |   8.56e1 | 7.72e1 |
| sumTailLazy   |   7.59e1 | 7.93e1 |    7.77e1 |        7.64e1 |   1.71e1 |   7.72e1 | 7.60e1 |
:end:

**** long list
#+begin_src sh :results drawer :exports both
perf-explore -r 100 -l 100000 --best --ticks
#+end_src

#+RESULTS:
:results:
|               | stepTime |   tick | tickForce | tickForceArgs | tickLazy | tickWHNF |  times |
| sumAux        |   2.71e6 | 2.37e6 |    2.38e6 |        2.68e6 |   1.70e1 |   2.38e6 | 4.68e6 |
| sumCata       |   2.81e6 | 3.01e6 |    2.78e6 |        3.61e6 |   1.69e1 |   2.81e6 | 3.18e6 |
| sumCo         |   2.34e6 | 2.34e6 |    5.36e6 |        2.35e6 |   1.73e1 |   2.35e6 | 2.34e6 |
| sumCoCase     |   2.36e6 | 2.44e6 |    2.40e6 |        2.36e6 |   1.67e1 |   5.26e6 | 2.33e6 |
| sumCoGo       |   2.79e6 | 2.79e6 |    2.79e6 |        2.82e6 |   1.64e1 |   3.19e6 | 2.78e6 |
| sumF          |   1.36e6 | 1.38e6 |    1.37e6 |        1.38e6 |   1.63e1 |   1.38e6 | 1.30e6 |
| sumFlip       |   7.47e5 | 7.51e5 |    7.54e5 |        7.62e5 |   1.61e1 |   7.66e5 | 7.60e5 |
| sumFlipLazy   |   9.97e5 | 1.00e6 |    1.00e6 |        9.96e5 |   1.70e1 |   1.00e6 | 1.00e6 |
| sumFoldr      |   2.97e6 | 2.80e6 |    3.19e6 |        2.78e6 |   1.71e1 |   6.04e6 | 3.58e6 |
| sumFuse       |   1.32e5 | 1.32e5 |    1.32e5 |        1.32e5 |   1.49e1 |   1.32e5 | 1.32e5 |
| sumFuseFoldl' |   1.32e5 | 1.32e5 |    1.32e5 |        1.32e5 |   1.51e1 |   1.32e5 | 1.32e5 |
| sumFuseFoldr  |   1.56e6 | 1.54e6 |    1.58e6 |        1.54e6 |   1.47e1 |   1.58e6 | 1.54e6 |
| sumFusePoly   |   1.92e5 | 1.92e5 |    1.92e5 |        1.92e5 |   1.48e1 |   1.92e5 | 1.92e5 |
| sumLambda     |   8.15e5 | 8.11e5 |    8.10e5 |        8.08e5 |   1.63e1 |   8.13e5 | 8.15e5 |
| sumMono       |   8.18e5 | 8.21e5 |    8.19e5 |        8.14e5 |   1.66e1 |   8.04e5 | 8.03e5 |
| sumPoly       |   8.09e5 | 8.16e5 |    8.17e5 |        8.12e5 |   1.71e1 |   8.12e5 | 8.10e5 |
| sumSum        |   7.97e5 | 7.86e5 |    7.80e5 |        7.96e5 |   1.70e1 |   7.83e5 | 7.84e5 |
| sumTail       |   7.46e5 | 8.13e5 |    8.10e5 |        7.47e5 |   1.66e1 |   8.11e5 | 7.48e5 |
| sumTailLazy   |   1.35e6 | 1.34e6 |    1.34e6 |        1.32e6 |   1.65e1 |   1.35e6 | 1.35e6 |
:end:

*** sums

#+begin_src sh :output drawer :exports both
perf-explore -r 1000 -l 1000 --sums
#+end_src

#+RESULTS:
|   | label1        | results |
|   | ---           |     --- |
|   | sumAux        | 16800.0 |
|   | sumCata       | 15600.0 |
|   | sumCo         | 18800.0 |
|   | sumCoCase     | 16300.0 |
|   | sumCoGo       | 15700.0 |
|   | sumF          | 10400.0 |
|   | sumFlip       | 10500.0 |
|   | sumFlipLazy   |  6940.0 |
|   | sumFoldr      | 18300.0 |
|   | sumFuse       |  1980.0 |
|   | sumFuseFoldl' |  1950.0 |
|   | sumFuseFoldr  | 14400.0 |
|   | sumFusePoly   |  1370.0 |
|   | sumLambda     |  9860.0 |
|   | sumMono       | 11200.0 |
|   | sumPoly       | 11100.0 |
|   | sumSum        | 11200.0 |
|   | sumTail       | 11400.0 |
|   | sumTailLazy   | 11000.0 |

*** lengths

#+begin_src sh :output drawer :exports both
perf-explore -r 1000 -l 1000 --lengths
#+end_src

#+RESULTS:
|   | label1           | results |
|   | ---              |     --- |
|   | lengthAux        | 10700.0 |
|   | lengthCo         | 10300.0 |
|   | lengthCoCase     | 10300.0 |
|   | lengthF          |  9110.0 |
|   | lengthFMono      |  9180.0 |
|   | lengthFlip       |  9850.0 |
|   | lengthFlipLazy   |  5470.0 |
|   | lengthFoldr      |  9500.0 |
|   | lengthFoldrConst | 10300.0 |
|   | lengthTail       | 12600.0 |
|   | lengthTailLazy   | 10700.0 |

** Gauge

#+begin_src sh :results output :exports both
perf-explore -r 1000 -l 1000 --average --gauge
#+end_src

#+RESULTS:
#+begin_example
sumFuse
benchmarking function ... function                                 time                 583.5 ns

benchmarking function ... function                                 time                 583.5 ns

sum
benchmarking function ... function                                 time                 3.691 μs

benchmarking function ... function                                 time                 3.645 μs

lengthF
benchmarking function ... function                                 time                 1.871 μs

benchmarking function ... function                                 time                 1.874 μs

constFuse
benchmarking function ... function                                 time                 293.0 ns

benchmarking function ... function                                 time                 299.8 ns

mapInc
benchmarking function ... function                                 time                 9.618 ns

benchmarking function ... function                                 time                 10.65 μs

noop
benchmarking function ... function                                 time                 5.254 ns

benchmarking function ... function                                 time                 5.249 ns

#+end_example

#+begin_src sh :results drawer :exports both
perf-explore --examples -r 10000 --averagesecs
#+end_src

#+RESULTS:
:results:
| label1    | results |
|-----------+---------|
| constFuse | 2.71e-7 |
| lengthF   | 3.24e-6 |
| mapInc    | 8.61e-9 |
| sum       | 3.76e-6 |
| sumFuse   | 8.18e-7 |
:end:

** Space

Data is collected from GHCStats

- allocated_bytes
- gcs
- gcdetails_live_bytes
- max_live_bytes
- max_mem_in_use_bytes

#+begin_src sh :results output :exports both
perf-explore -r 10 -l 100000 --time +RTS -T -RTS
#+end_src

| label1 | label2 | results |
|--------+--------+---------|
| sum    |      0 |  1.74e7 |
| sum    |      1 |  9.43e5 |
| sum    |      2 |  9.62e5 |
| sum    |      3 |  9.25e5 |
| sum    |      4 |  8.04e5 |
| sum    |      5 |  8.15e5 |
| sum    |      6 |  8.14e5 |
| sum    |      7 |  8.20e5 |
| sum    |      8 |  8.52e5 |
| sum    |      9 |  8.37e5 |

#+begin_src sh :results output :exports both
perf-explore -r 10 -l 100000 --space +RTS -T -RTS
#+end_src

#+RESULTS:
#+begin_example
|label1|label2|allocated|gcollects|maxLiveBytes|gcLiveBytes|MaxMem|
|---|---|---|
|sum|0|7.25e6|7|3.94e6|3.94e6|1.05e7|
|sum|1|0|0|0|0|0|
|sum|2|0|0|0|0|0|
|sum|3|0|0|0|0|0|
|sum|4|0|0|0|0|0|
|sum|5|0|0|0|0|0|
|sum|6|0|0|0|0|0|
|sum|7|0|0|0|0|0|
|sum|8|0|0|0|0|0|
|sum|9|0|0|0|0|0|
#+end_example

*** spacetime

#+begin_src sh :results output :exports both
perf-explore -r 10 -l 100000 --spacetime +RTS -T -RTS
#+end_src

#+RESULTS:
#+begin_example
|label1|label2|time|allocated|gcollects|maxLiveBytes|gcLiveBytes|MaxMem|
|---|---|---|
|sum|0|2.99e7|7.25e6|7|3.94e6|3.94e6|1.05e7|
|sum|1|1.06e6|0|0|0|0|0|
|sum|2|9.96e5|0|0|0|0|0|
|sum|3|9.98e5|0|0|0|0|0|
|sum|4|9.92e5|0|0|0|0|0|
|sum|5|1.00e6|0|0|0|0|0|
|sum|6|9.91e5|0|0|0|0|0|
|sum|7|1.02e6|0|0|0|0|0|
|sum|8|1.00e6|0|0|0|0|0|
|sum|9|1.00e6|0|0|0|0|0|
#+end_example

*** slop

#+begin_src haskell :results output :exports both
import qualified Data.Map.Strict as Map
(\m -> (Map.!) m "slop") . fst . snd <$> slops 10 time (sum |$| [1..1000])
#+end_src

#+RESULTS:
: Cycles {word = 5487960}

** Perf.Degrade

#+begin_src sh :results drawer :exports both
perf-explore -r 1000 -l 1000 --examples --check
#+end_src

#+RESULTS:
:results:
| constFuse | 1.31e3 | 6.71e2 | improvement       |
| lengthF   | 9.37e3 | 9.14e3 |                              |
| mapInc    | 2.89e1 | 3.06e1 | slightly degraded |
| sum       | 1.27e4 | 1.11e4 | improvement       |
| sumFuse   | 2.84e3 | 2.05e3 | improvement       |
:end:

** Resources

[[https://en.wikipedia.org/wiki/Time_Stamp_Counter][rdtsc]]

** BigO

We could do a regression and minimise the error tern, but we know that the largest run contains the most information; we would need to weight the simulations according to some heuristic.

Instead, we:

- estimate the order factor for each possible Order, from N3 to N0, setting the highest n run constant factor to zero,
- pick the order based on lowest absolute error result summed across all the runs,

#+begin_src haskell :results output :exports both
sims = 100
ns = [1,10,100,1000,10000]
ms <- tcurve StatBest sims (\x -> sum [1..x]) ns
ms
(o',res) = estO ns ms
o'
res
#+end_src

#+RESULTS:
:
: >  > [2723.1340382522158,3193.0,8273.0,92495.53333333334,931010.0]
: > Order {factors = [0.0,0.0,0.0,0.0,93.101,0.0,0.0,0.0]}
: [2630.0330382522156,2261.99,-1037.1000000000004,-605.4666666666599,0.0]


#+begin_src haskell
estOrder (\x -> sum [1..x]) 100 [1,10,100,1000,10000]
#+end_src

#+RESULTS:
: Order {factors = [0.0,0.0,0.0,0.0,1.0852114021956238e-2,0.0,0.0,0.0]}
