#+TITLE: perf

~perf~ provides some ideas, code and a library for low-level performance measurement for Haskell hacking. The library focuses on using the rdtsc instruction set that comes with the x86 chip to measure performance as number of cycles.

* Usage


#+begin_src haskell
import Perf
#+end_src

* setup

Running this readme.org is very slow compared with an external process which accesses the compiled version of the library.

#+begin_src haskell :results output
:set prompt " > "
:set -Wno-type-defaults
:set -Wno-name-shadowing
:set -XOverloadedStrings
#+end_src

#+RESULTS:

#+begin_src haskell :results output
import Perf
import Perf.Stats
import NumHask.Space (quantile)
import Data.FormatN
import Perf.Cycle
import Prelude as P
import Data.Foldable
import qualified Data.Text as Text
import qualified Data.Text.IO as Text
#+end_src

#+RESULTS:

* tick

The fundamental operation of Perf.Cycle is tick, which sandwiches a (strict) function application between two readings of the rdstc chip.

#+begin_src haskell
:t tick
#+end_src

#+RESULTS:
: tick :: (a -> b) -> a -> IO (Cycle, b)

tick returns in the IO monad, because reading a cycle counter is an IO effect. The trivial but fundamental point is that performance measurement effects the computation being measured.

Unlike benchmarking-style libraries, such as criterion, the result of the computation is passed through along with the cycle count. In this way, the `Perf` monad can be inserted into the midst of a computation in an attempt to measure performance in-situ as opposed to sitting off in a separate and perhaps unrepresentative process.

* tick_

tick_ measures the number of cycles between two clock reads.

#+begin_src haskell
:t tick_
#+end_src

#+RESULTS:
: tick_ :: IO Cycle

#+begin_src haskell
replicateM 10 tick_
#+end_src

#+RESULTS:
| 8530 | 910 | 730 | 668 | 642 | 648 | 644 | 642 | 646 | 640 |

* function application

#+begin_src haskell
fmap (fmap fst) . replicateM 10 $ tick (const ()) ()
#+end_src

#+RESULTS:
| 8610 | 3654 | 2900 | 2932 | 2672 | 2708 | 2684 | 2664 | 2582 | 2652 |

Here, ~const () ()~ was evaluated and took 6.7k cycles for the first effect, reducing down to 2.2k after 10 effects. What it did in that time we will never know, really, at least from usage of ~perf~. 2.2k cycles is, on my 2.5GHz machine equal to 2200 / 2.5e9 = 8.8e-7 of a second or 880 nanoseconds.

Alternatively, ~tickIO~ measures the evaluation of an IO value.

#+begin_src haskell
:t tickIO
#+end_src

#+RESULTS:
: tickIO :: IO a -> IO (Cycle, a)

#+begin_src haskell
fmap (fmap fst) . replicateM 10 $ tickIO (pure ())
#+end_src

#+RESULTS:
| 5840 | 2602 | 1910 | 1698 | 1668 | 1660 | 1672 | 1676 | 1680 | 1662 |

#+begin_src haskell
ticks 100 (const ()) ()
#+end_src

#+RESULTS:
| 8226 | 3298 | 3254 | 2686 | 2694 | 2724 | 2868 | 2732 | 2644 | 2678 | 2680 | 2896 | 2734 | 2606 | 2608 | 2598 | 2606 | 2738 | 2742 | 2610 | 2554 | 2532 | 2576 | 2592 | 2600 | 2562 | 2786 | 2592 | 2646 | 2624 | 2666 | 2640 | 2640 | 2602 | 2672 | 2560 | 3478 | 2556 | 2552 | 2572 | 2622 | 2492 | 2572 | 2706 | 2544 | 2604 | 2748 | 2570 | 2596 | 3078 | 2666 | 2592 | 2612 | 2648 | 2594 | 2564 | 2716 | 2564 | 2594 | 2596 | 2554 | 2766 | 2552 | 3026 | 2602 | 2860 | 2632 | 2614 | 2620 | 2586 | 3014 | 2626 | 2626 | 2614 | 2830 | 2624 | 2616 | 2648 | 2610 | 2626 | 2610 | 2590 | 2930 | 2622 | 2732 | 2698 | 3004 | 2664 | 2948 | 2630 | 2588 | 2766 | 2726 | 2600 | 2634 | 2792 | 2704 | 2774 | 2638 | 2634 |

* sum example

#+begin_src haskell
fmap (comma (Just 3) . fromIntegral) . fst <$> ticks 10 sum ([1..10000] :: [Double])
#+end_src

#+RESULTS:
| 3,680,000 | 5,020,000 | 726,000 | 693,000 | 2,880,000 | 746,000 | 671,000 | 1,730,000 | 626,000 | 618,000 |


#+begin_src haskell
ts <- ticks 10000 sum ([1..1000] :: [Double])
putStrLn $ Text.unpack $ average (fst ts)
#+end_src

#+RESULTS:
: <interactive>:42:26-32: error:
:     Variable not in scope: average :: [Cycle] -> Text.Text

#+begin_src haskell
:set -XAllowAmbiguousTypes

fMono :: Int -> Int
fMono x = foldl' (+) 0 [1 .. x]

fPoly :: (Enum b, Num b, Additive b) => b -> b
fPoly x = foldl' (+) 0 [1 .. x]

fLambda :: Int -> Int
fLambda = \x -> foldl' (+) 0 [1 .. x]
#+end_src

#+begin_src haskell
fmap (median . fst) (ticks 1000 fMono 1000)
#+end_src

#+RESULTS:
: )’
: "69,200"

#+begin_src haskell
fmap (median . fst) $ ticks 1000 fPoly 1000
#+end_src

#+RESULTS:
: )’
: "65,400"

#+begin_src haskell
fmap (median . fst) $ ticks 1000 fLambda 1000
#+end_src

#+RESULTS:
: )’
: "64,300"

* compiled performance

** baseline callibration

#+begin_src sh :results output
perf-basic --help
#+end_src

#+RESULTS:
#+begin_example
basic perf callibration

Usage: perf-basic (-r|--runs ARG) [-b|--include basic effect measurements]
                  (-l|--length ARG) [--best | --median | --average]
  perf benchmarking

Available options:
  -r,--runs ARG            number of runs to perform
  -l,--length ARG          length of list
  --best                   report upper decile
  --median                 report median
  --average                report average
  -h,--help                Show this help text
#+end_example

#+begin_src sh :results output
perf-basic -b -r 10000 --average -l 1000
#+end_src

#+RESULTS:
#+begin_example
tick_: [16,14,14,14,14,14,16,16,16,16]
tick_: 16.6
const (): [16,14,14,14,14,16,16,16,16,16]
tick (const ()): 16.4
tickIO (pure ()): 16.1
fa: 8,940
sum: 10,700
sum': 7,300
fApp_: 664
fSum_ 674
fMono: 9,400
fPoly: 10,700
fLambda: 6,830
#+end_example

#+begin_src sh :results output
ghc app/basic.hs -O2
./app/basic -b -r 10000 --average -l 1000
#+end_src

#+RESULTS:
#+begin_example
Loaded package environment from /Users/tonyday/haskell/perf/.ghc.environment.x86_64-darwin-8.10.7
tick_: [18,18,18,18,18,22,20,20,18,18]
tick_: 19.0
const (): [30,18,20,18,20,18,20,20,20,20]
tick (const ()): 19.0
tickIO (pure ()): 18.9
fa: 8,970
sum: 10,700
sum': 7,190
fApp_: 665
fSum_ 673
fMono: 9,400
fPoly: 10,700
fLambda: 6,890
#+end_example

* Resources

[[https://en.wikipedia.org/wiki/Time_Stamp_Counter][rdtsc]]


* ToDo zipping

#+begin_src haskell
-- * zipping
-- from https://doisinkidney.com/posts/2019-05-08-list-manipulation-tricks.html

-- what is the name of this type of recursion?
zipRec :: [a] -> [b] -> [(a,b)]
zipRec [] _ = []
zipRec _ [] = []
zipRec (x:xs) (y:ys) = (x,y) : zipRec xs ys

-- step 1: write as a case statement on the first argument

zipCase :: [a] -> [b] -> [(a,b)]
zipCase xs = case xs of
  [] -> const []
  (x:xs') -> \case
    [] -> []
    (y:ys) -> (x,y):zipCase xs' ys

-- step 2: rewrite the case statements as auxillary functions
zipAux :: [a] -> [b] -> [(a,b)]
zipAux xs = case xs of
  [] -> b
  (x:xs') -> f x xs'
  where
    b _ = []
    f x xs' = \case
      [] -> []
      (y:ys) -> (x,y):zipAux xs' ys

-- step 3: refactor the recursive call to the first case expression
zipRef :: [a] -> [b] -> [(a,b)]
zipRef xs = case xs of
  [] -> b
  (x:xs') -> f x (zipRef xs')
  where
    b _ = []
    f x xs' = \case
      [] -> []
      (y:ys) -> (x,y): xs' ys

-- step 4 pass the auxillary functions to foldr
-- zipR :: [a] -> [b] -> [(a,b)]
zipR :: [a] -> [b] -> [(a, b)]
zipR = foldr f b
  where
    b _ = []
    f x xs = \case
      [] -> []
      (y:ys) -> (x,y): xs ys

zipR' :: [a] -> [b] -> [(a, b)]
zipR' = foldr f (const [])
  where
    f x xs ys = case ys of
      [] -> []
      (y:ys') -> (x,y): xs ys'

-- from https://doisinkidney.com/posts/2020-08-22-some-more-list-algorithms.html
newtype Zip a b =
  Zip { runZip :: a -> (Zip a b -> b) -> b }

zipZ :: [a] -> [b] -> [(a,b)]
zipZ xs ys = foldr xf (const []) xs (Zip (foldr yf yb ys))
  where
    xf x xk yk = runZip yk x xk

    yf y yk x xk = (x,y) : xk (Zip yk)
    yb _ _ = []

newtype a -&> b = Hyp { invoke :: (b -&> a) -> b }

{-
FIXME:

zipHyp :: forall a b. [a] -> [b] -> [(a,b)]
zipHyp xs ys = invoke xz yz
  where
    xz :: (a -> [(a,b)]) -&> [(a,b)]
    xz = foldr f b xs
      where
        f x xk = Hyp (\yk -> invoke yk xk x)
        b = Hyp (\_ -> [])

    yz :: [(a,b)] -&> (a -> [(a,b)])
    yz = foldr f b ys
      where
        f y yk = Hyp (\xk x -> (x,y) : invoke xk yk)
        b = Hyp (\_ _ -> [])

-}

-- a -&> a ~ Fix (Cont a)
newtype HypP p a b = HypP { invokeP :: p (HypP p b a) b }
newtype HypM m a b = HypM { invokeM :: m ((HypM m a b -> a) -> b) }
#+end_src
