#+TITLE: perf
#+PROPERTY: header-args :exports both
#+PROPERTY: header-args :eval no-export

* perf
:PROPERTIES:
:EXPORT_FILE_NAME: perf
:export_date: 2022-4-12
:END:

** intro

~perf~ provides some ideas, code and a library for low-level performance measurement for Haskell hacking. The library:

- provides a monad transformer, ~PerfT~, as a light-weight wrapper for use on existing code. ~PerfT~ modifications can be included in code bases, as opposed to performance being separated code and  process, with any effects able to be erased at compile time with ~evalPerfT~.

- focuses on using the rdtsc instruction set that comes with the x86 chip to measure accurate time performance as number of clock cycles.

- abstracts the concept of what is being measured, so that concepts such as counters, debug checks, time and space performance can be treated equivalently.

** Setup

Note that running this readme.org is very slow compared with an external process which accesses the compiled version of the library.

#+begin_src haskell :results output :exports both
:r
:set prompt " > "
:set -Wno-type-defaults
:set -Wno-name-shadowing
:set -XOverloadedStrings
import Perf
import Data.FormatN
import qualified Data.Text as Text
import qualified Data.Map.Strict as Map
putStrLn "ok"
#+end_src

#+RESULTS:
#+begin_example
Resolving dependencies...
Build profile: -w ghc-8.10.7 -O1
In order, the following will be built (use -v for more details):
 - perf-0.10.0 (lib) (file src/Perf/Report.hs changed)
Preprocessing library for perf-0.10.0..
GHCi, version 8.10.7: https://www.haskell.org/ghc/  :? for help
Loaded GHCi configuration from /Users/tonyday/haskell/perf/.ghci
[1 of 9] Compiling Perf.Stats       ( src/Perf/Stats.hs, interpreted )
[2 of 9] Compiling Perf.Types       ( src/Perf/Types.hs, interpreted )
[3 of 9] Compiling Perf.Time        ( src/Perf/Time.hs, interpreted )
[4 of 9] Compiling Perf.Space       ( src/Perf/Space.hs, interpreted )
[5 of 9] Compiling Perf.Measure     ( src/Perf/Measure.hs, interpreted )
[6 of 9] Compiling Perf.BigO        ( src/Perf/BigO.hs, interpreted )
[7 of 9] Compiling Perf.Algos       ( src/Perf/Algos.hs, interpreted )
[8 of 9] Compiling Perf.Report      ( src/Perf/Report.hs, interpreted )
[9 of 9] Compiling Perf             ( src/Perf.hs, interpreted )
Ok, 9 modules loaded.
> Ok, 9 modules loaded.
>  >  >  >  >  >  >  > ok
#+end_example

** Time
*** What is a tick?

The fundamental operation of Perf.Time is tick, which sandwiches a (strict) function application between two readings of the rdstc chip.

#+begin_src haskell :results output :exports both
:t tick
#+end_src

#+RESULTS:
: tick :: (a -> b) -> a -> IO (Cycles, b)

tick returns in the IO monad, because reading a cycle counter is an IO effect. The trivial but fundamental point is that performance measurement effects the computation being measured.

Unlike benchmarking-style libraries, such as criterion, the result of the computation is passed through along with the cycle count. In this way, the `Perf` monad can be inserted into the midst of a computation in an attempt to measure performance in-situ as opposed to sitting off in a separate and perhaps unrepresentative process.

*** tick_

tick_ measures the number of cycles between two clock reads.

#+begin_src haskell :results output :exports both
:t tick_
#+end_src

#+RESULTS:
: tick_ :: IO Cycles

#+begin_src haskell :results output :exports both
fmap word <$> replicateM 10 tick_
#+end_src

#+RESULTS:
: [3738,1000,830,850,796,824,806,818,772,802]

*** multiple ticks

#+begin_src haskell :results output :exports both
fmap (fmap (word . fst)) . replicateM 10 $ tick (const ()) ()
#+end_src

#+RESULTS:
: [7740,3688,2716,2632,2642,2916,2852,2646,2630,2624]

Here, ~const () ()~ was evaluated and took 7.7k cycles for the first effect, reducing down to 2.6k after 10 effects. What it did in that time we will never know, really, at least from usage of ~perf~. 2.2k cycles is, on my 2.5GHz machine equal to 2200 / 2.5e9 = 8.8e-7 of a second or 880 nanoseconds.

*** tickIO

~tickIO~ measures the evaluation of an IO value.

#+begin_src haskell :results output :exports both
:t tickIO
#+end_src

#+RESULTS:
: tickIO :: IO a -> IO (Cycles, a)

#+begin_src haskell :results output :exports both
fmap (fmap (word . fst)) . replicateM 10 $ tickIO (pure ())
#+end_src

#+RESULTS:
: [6090,2462,1854,1778,1766,1684,1696,1716,1690,1706]

*** sum example

#+begin_src haskell :exports both
fmap (expt (Just 2) . fromIntegral) . fst <$> ticks 10 sum ([1..10000] :: [Double])
#+end_src

#+RESULTS:
| 1.8e6 | 1.3e6 | 1.3e6 | 9.3e6 | 6.8e5 | 6.4e5 | 2.8e6 | 6.6e5 | 6.3e5 | 1.6e6 |


#+begin_src haskell :results output :exports both
ts <- ticks 10000 sum ([1..1000] :: [Double])
print $ average (fmap fromIntegral $ fst ts)
#+end_src

#+RESULTS:
:
: 55690.3084

** PerfT

~PerfT~ allows for multiple measurement points and is polymorphic in what is being measured. It returns a Map of results held in State.

Compare a lower-level usage of ticks, measuring the average of summing to one thousand over one thousand trials:

#+begin_src haskell :results output :exports both
import Data.Bifunctor
first (average . fmap fromIntegral) <$> ticks 1000 sum [1..1000]
#+end_src

#+RESULTS:
:
: (67196.398,500500)

... with PerfT usage

#+begin_src haskell :results output :exports both
second (fmap (average . fmap fromIntegral)) <$> runPerfT (times 1000) (sum |$| [1..1000])
#+end_src

#+RESULTS:
: (500500,fromList [("",67159.27)])

Comparing performance of sum versus a list fusion approach:

#+begin_src haskell :results output :exports both
fmap (average . fmap fromIntegral) <$> (execPerfT (times 1000) $ do; (fap "sum" sum [1..1000]); (fap "fusion" (\x -> sum [1..x]) 1000))
#+end_src

#+RESULTS:
: fromList [("fusion",107226.43),("sum",59301.402)]

An IO example

#+begin_src haskell
exampleIO' :: IO ()
exampleIO' = do
  txt <- Text.readFile "src/Perf.hs"
  let n = Text.length txt
  Text.putStrLn $ "length of file is: " <> Text.pack (show n)
#+end_src

#+begin_src haskell :results output :exports both
exampleIO = execPerfT time (do
  txt <- fam "file_read" (Text.readFile "src/Perf.hs")
  n <- fap "length" Text.length txt
  fam "print_result" (Text.putStrLn $ "length of file is: " <> Text.pack (show n)))
#+end_src

#+begin_src sh :exports both
perf-explore --exampleIO --check --record
#+end_src

#+RESULTS:
| normal | file-read    | time | 384000.0 | 454000.0 | slightly | degraded |
| normal | length       | time |   5330.0 |   5120.0 |          |          |
| normal | print-result | time |  39500.0 |  40000.0 |          |          |
| outer  | file-read    | time |  80600.0 |  84500.0 |          |          |
| outer  | length       | time |   5090.0 |   5010.0 |          |          |
| outer  | outer-total  | time |  98200.0 | 102000.0 |          |          |
| outer  | print-result | time |   4900.0 |   4960.0 |          |          |

** perf-explore

~perf-explore~ contains some exploratory routines to help develop =perf=

#+begin_src sh :results output :exports both
perf-explore --help
#+end_src

#+RESULTS:
#+begin_example
basic perf callibration

Usage: perf-explore [-n|--runs ARG] [-l|--length ARG]
                    [--best | --median | --average | --averagesecs]
                    [--sums | --lengths | --examples | --example | --exampleIO |
                      --noops | --ticks | --gauge]
                    [--time | --space | --spacetime | --allocation]
                    [--sumFuse | --sum | --lengthF | --constFuse | --mapInc |
                      --noOp] [-g|--golden ARG] [-r|--record] [-c|--check]

  perf benchmarking

Available options:
  -n,--runs ARG            number of runs to perform
  -l,--length ARG          length of list
  --best                   report upper decile
  --median                 report median
  --average                report average
  --averagesecs            report average in seconds
  --sums                   run on sum algorithms
  --lengths                run on length algorithms
  --examples               run on example algorithms
  --example                run on the example algorithm
  --exampleIO              exampleIO test
  --noops                  noops test
  --ticks                  tick test
  --gauge                  gauge runs on exmaple for comparison
  --time                   measure time performance
  --space                  measure space performance
  --spacetime              measure both space and time performance
  --allocation             measure bytes allocated
  --sumFuse                fused sum pipeline
  --sum                    sum
  --lengthF                foldr id length
  --constFuse              fused const pipeline
  --mapInc                 fmap (+1)
  --noOp                   const ()
  -g,--golden ARG          golden file name
  -r,--record              record the result to a golden file
  -c,--check               check versus a golden file
  -h,--help                Show this help text
#+end_example

#+begin_src haskell :results output :exports both
fmap averageI <$> execPerfT (times 10000) (sum |$| [1..1000])
#+end_src

#+RESULTS:
: fromList [("",57471.7402)]

The equivalent to the above code is:

#+begin_src sh :results drawer :exports both
perf-explore -n 10000 -l 1000 --sum
#+end_src

#+RESULTS:
:results:
| label1 | label2 | results |
|--------+--------+---------|
| sum    | time   |  3.10e4 |
:end:

*** noops

#+begin_src sh :results drawer :exports both
perf-explore --noops
#+end_src

#+RESULTS:
:results:
| label1 | label2  | label3 | results |
|--------+---------+--------+---------|
| const  | 1st     | time   |  4.94e3 |
| const  | 2nd     | time   |  3.20e1 |
| const  | 3rd     | time   |  1.60e1 |
| const  | 4th     | time   |  1.80e1 |
| const  | average | time   |  2.39e1 |
| const  | best    | time   |  1.57e1 |
| const  | median  | time   |  1.78e1 |
| pure   | 1st     | time   |  4.25e3 |
| pure   | 2nd     | time   |  3.80e1 |
| pure   | 3rd     | time   |  3.80e1 |
| pure   | 4th     | time   |  2.20e1 |
| pure   | average | time   |  2.53e1 |
| pure   | best    | time   |  1.77e1 |
| pure   | median  | time   |  2.00e1 |
:end:

#+begin_src haskell :results output :exports both
:r
:set -XOverloadedLabels
import qualified Data.Text as Text
import qualified Data.Map.Strict as Map
import Chart
import Prelude
import Optics.Core
m <- read <$> readFile "other/noop.map" :: IO (Map.Map Text.Text [Cycles])
let (Just d) = Map.lookup "fap times" m
filter (> 100) d
#+end_src

#+RESULTS:
: Ok, 8 modules loaded.
: >  >  >  >  >  >  >
: <interactive>:202:5: warning: [-Wincomplete-uni-patterns]
:     Pattern match(es) are non-exhaustive
:     In a pattern binding: Patterns not matched: Nothing
: [Cycles {word = 484},Cycles {word = 128},Cycles {word = 136},Cycles {word = 128},Cycles {word = 314}]

#+begin_src haskell :file other/noop.svg :results output graphics file :exports both
writeChartSvg "other/noop.svg" $ mempty & #hudOptions .~ colourHudOptions (rgb light) defaultHudOptions & #charts .~ unnamed [(RectChart (defaultRectStyle & #borderSize .~ 0 & #color .~ Colour 1 1 1 1) (zipWith (\y x -> Rect x (x+1) 0 y) (fromIntegral <$> filter (<= 100) d) [0..]))]
#+end_src

#+RESULTS:
[[file:other/noop.svg]]

*** measurement context

Exploration of how the code surrounding measurement effects performance.

#+begin_src sh :results drawer
perf-explore -n 1000 -l 1000 --ticks
#+end_src

#+RESULTS:
:results:
|               | stepTime |   tick | tickForce | tickForceArgs | tickLazy | tickWHNF |  times |
| sumAux        |   2.33e4 | 1.78e4 |    3.00e4 |        2.33e4 |   1.68e1 |   1.64e4 | 2.32e4 |
| sumCata       |   1.57e4 | 1.63e4 |    1.59e4 |        1.53e4 |   1.64e1 |   1.55e4 | 1.54e4 |
| sumCo         |   1.77e4 | 2.46e4 |    1.80e4 |        1.76e4 |   1.73e1 |   1.89e4 | 1.77e4 |
| sumCoCase     |   1.69e4 | 1.79e4 |    1.69e4 |        1.62e4 |   1.68e1 |   1.63e4 | 1.65e4 |
| sumCoGo       |   1.90e4 | 1.92e4 |    1.91e4 |        1.87e4 |   1.69e1 |   1.87e4 | 1.87e4 |
| sumF          |   1.22e4 | 1.05e4 |    1.22e4 |        1.22e4 |   1.74e1 |   1.04e4 | 1.23e4 |
| sumFlip       |   1.23e4 | 1.06e4 |    1.22e4 |        1.24e4 |   1.69e1 |   1.52e4 | 1.21e4 |
| sumFlipLazy   |   1.29e4 | 1.20e4 |    1.07e4 |        1.06e4 |   1.77e1 |   1.11e4 | 1.46e4 |
| sumFoldr      |   1.91e4 | 1.93e4 |    1.92e4 |        1.87e4 |   1.72e1 |   1.87e4 | 1.87e4 |
| sumFuse       |   1.35e3 | 1.35e3 |    1.35e3 |        1.35e3 |   1.92e1 |   3.15e3 | 1.35e3 |
| sumFuseFoldl' |   1.35e3 | 1.35e3 |    1.35e3 |        1.35e3 |   1.92e1 |   1.37e3 | 1.35e3 |
| sumFuseFoldr  |   8.64e3 | 9.59e3 |    9.04e3 |        8.84e3 |   1.92e1 |   8.68e3 | 8.73e3 |
| sumFusePoly   |   2.04e3 | 1.97e3 |    1.97e3 |        1.98e3 |   1.92e1 |   1.97e3 | 1.97e3 |
| sumLambda     |   1.11e4 | 1.12e4 |    1.13e4 |        1.13e4 |   1.77e1 |   1.12e4 | 1.14e4 |
| sumMono       |   1.12e4 | 1.12e4 |    1.11e4 |        1.10e4 |   1.70e1 |   1.17e4 | 1.12e4 |
| sumPoly       |   1.10e4 | 1.13e4 |    1.12e4 |        1.11e4 |   1.84e1 |   1.10e4 | 1.85e4 |
| sumSum        |   1.26e4 | 1.12e4 |    1.28e4 |        1.24e4 |   1.75e1 |   1.13e4 | 1.25e4 |
| sumTail       |   1.07e4 | 1.15e4 |    1.12e4 |        1.08e4 |   1.74e1 |   1.12e4 | 1.08e4 |
| sumTailLazy   |   1.16e4 | 1.11e4 |    1.17e4 |        1.19e4 |   1.72e1 |   1.10e4 | 1.18e4 |
:end:


#+begin_src sh :results drawer
perf-explore -n 100000 -l 1000 --ticks
#+end_src

#+RESULTS:
:results:
|               | stepTime |   tick | tickForce | tickForceArgs | tickLazy | tickWHNF |  times |
| sumAux        |   2.00e4 | 1.93e4 |    2.08e4 |        1.94e4 |   1.70e1 |   1.93e4 | 1.94e4 |
| sumCata       |   2.08e4 | 2.05e4 |    2.07e4 |        2.11e4 |   1.70e1 |   2.27e4 | 2.12e4 |
| sumCo         |   1.93e4 | 1.89e4 |    1.88e4 |        1.89e4 |   1.69e1 |   1.88e4 | 1.88e4 |
| sumCoCase     |   1.68e4 | 1.84e4 |    1.62e4 |        1.65e4 |   1.69e1 |   1.84e4 | 1.62e4 |
| sumCoGo       |   2.15e4 | 2.09e4 |    2.09e4 |        2.09e4 |   1.70e1 |   2.21e4 | 2.09e4 |
| sumF          |   9.48e3 | 8.98e3 |    8.71e3 |        9.14e3 |   1.69e1 |   8.69e3 | 9.00e3 |
| sumFlip       |   8.61e3 | 8.69e3 |    8.62e3 |        8.60e3 |   1.74e1 |   9.83e3 | 8.61e3 |
| sumFlipLazy   |   5.67e3 | 8.94e3 |    9.18e3 |        5.95e3 |   1.69e1 |   8.61e3 | 5.55e3 |
| sumFoldr      |   2.15e4 | 2.14e4 |    2.09e4 |        2.10e4 |   1.71e1 |   2.13e4 | 2.10e4 |
| sumFuse       |   1.36e3 | 1.61e3 |    1.50e3 |        1.38e3 |   1.95e1 |   1.43e3 | 1.37e3 |
| sumFuseFoldl' |   1.36e3 | 1.60e3 |    1.37e3 |        1.56e3 |   1.95e1 |   1.41e3 | 1.38e3 |
| sumFuseFoldr  |   1.15e4 | 1.12e4 |    1.13e4 |        1.13e4 |   1.93e1 |   1.16e4 | 1.34e4 |
| sumFusePoly   |   2.19e3 | 2.25e3 |    2.22e3 |        2.00e3 |   1.93e1 |   2.04e3 | 2.24e3 |
| sumLambda     |   8.82e3 | 9.05e3 |    8.58e3 |        8.74e3 |   1.71e1 |   8.58e3 | 8.82e3 |
| sumMono       |   5.68e3 | 6.06e3 |    5.69e3 |        5.90e3 |   1.79e1 |   5.96e3 | 5.72e3 |
| sumPoly       |   1.15e4 | 8.97e3 |    9.40e3 |        8.98e3 |   1.70e1 |   9.14e3 | 9.02e3 |
| sumSum        |   8.04e3 | 8.92e3 |    8.24e3 |        8.03e3 |   1.69e1 |   8.38e3 | 8.09e3 |
| sumTail       |   5.84e3 | 6.10e3 |    5.83e3 |        5.84e3 |   1.69e1 |   8.09e3 | 5.96e3 |
| sumTailLazy   |   1.20e4 | 1.04e4 |    1.27e4 |        1.21e4 |   1.69e1 |   1.21e4 | 1.21e4 |
:end:

**** short list
#+begin_src sh :results drawer :exports both
perf-explore -n 10000 -l 10 --best --ticks
#+end_src

#+RESULTS:
:results:
|               | stepTime |   tick | tickForce | tickForceArgs | tickLazy | tickWHNF |  times |
| sumAux        |   9.30e1 | 9.41e1 |    9.40e1 |        9.34e1 |   1.50e1 |   9.55e1 | 9.29e1 |
| sumCata       |   9.13e1 | 8.82e1 |    9.13e1 |        9.13e1 |   1.50e1 |   9.13e1 | 8.96e1 |
| sumCo         |   9.52e1 | 9.44e1 |    9.50e1 |        9.54e1 |   1.51e1 |   9.53e1 | 9.20e1 |
| sumCoCase     |   9.56e1 | 9.34e1 |    9.46e1 |        9.54e1 |   1.51e1 |   9.51e1 | 9.19e1 |
| sumCoGo       |   9.13e1 | 8.81e1 |    9.15e1 |        9.13e1 |   1.50e1 |   9.14e1 | 8.95e1 |
| sumF          |   6.36e1 | 6.54e1 |    6.71e1 |        6.59e1 |   1.50e1 |   6.54e1 | 6.37e1 |
| sumFlip       |   6.53e1 | 6.59e1 |    6.71e1 |        6.56e1 |   1.51e1 |   6.57e1 | 6.48e1 |
| sumFlipLazy   |   6.59e1 | 6.60e1 |    6.67e1 |        6.74e1 |   1.50e1 |   6.54e1 | 6.43e1 |
| sumFoldr      |   9.13e1 | 8.81e1 |    9.13e1 |        9.11e1 |   1.47e1 |   9.13e1 | 8.93e1 |
| sumFuse       |   2.36e1 | 2.36e1 |    2.48e1 |        2.54e1 |   1.71e1 |   2.63e1 | 2.57e1 |
| sumFuseFoldl' |   2.37e1 | 2.36e1 |    2.52e1 |        2.56e1 |   1.71e1 |   2.62e1 | 2.54e1 |
| sumFuseFoldr  |   4.35e1 | 4.44e1 |    4.37e1 |        4.92e1 |   1.71e1 |   4.79e1 | 4.92e1 |
| sumFusePoly   |   4.78e1 | 4.95e1 |    4.78e1 |        5.11e1 |   1.71e1 |   5.02e1 | 5.10e1 |
| sumLambda     |   8.58e1 | 8.73e1 |    8.57e1 |        8.69e1 |   1.50e1 |   8.58e1 | 8.36e1 |
| sumMono       |   7.31e1 | 7.15e1 |    7.32e1 |        7.32e1 |   1.50e1 |   7.26e1 | 7.10e1 |
| sumPoly       |   8.74e1 | 8.71e1 |    8.57e1 |        8.58e1 |   1.49e1 |   8.54e1 | 8.35e1 |
| sumSum        |   8.55e1 | 8.68e1 |    8.58e1 |        8.66e1 |   1.50e1 |   8.63e1 | 8.33e1 |
| sumTail       |   7.55e1 | 7.53e1 |    7.60e1 |        7.72e1 |   1.50e1 |   7.64e1 | 7.52e1 |
| sumTailLazy   |   7.94e1 | 7.76e1 |    7.92e1 |        7.85e1 |   1.50e1 |   7.85e1 | 7.57e1 |
:end:

**** long list
#+begin_src sh :results drawer :exports both
perf-explore -n 100 -l 100000 --best --ticks
#+end_src

#+RESULTS:
:results:
|               | stepTime |   tick | tickForce | tickForceArgs | tickLazy | tickWHNF |  times |
| sumAux        |   2.31e6 | 2.34e6 |    2.70e6 |        2.30e6 |   1.52e1 |   3.15e6 | 4.29e6 |
| sumCata       |   2.80e6 | 2.76e6 |    5.39e6 |        3.64e6 |   1.50e1 |   2.76e6 | 2.75e6 |
| sumCo         |   2.95e6 | 2.30e6 |    4.36e6 |        4.84e6 |   1.49e1 |   2.40e6 | 2.97e6 |
| sumCoCase     |   2.31e6 | 2.30e6 |    2.32e6 |        2.33e6 |   1.51e1 |   2.29e6 | 2.28e6 |
| sumCoGo       |   3.55e6 | 2.76e6 |    2.75e6 |        2.77e6 |   1.47e1 |   3.12e6 | 2.79e6 |
| sumF          |   7.76e5 | 7.79e5 |    7.82e5 |        7.80e5 |   1.51e1 |   7.77e5 | 6.76e5 |
| sumFlip       |   7.47e5 | 7.46e5 |    7.44e5 |        7.48e5 |   1.51e1 |   7.44e5 | 7.46e5 |
| sumFlipLazy   |   1.26e6 | 1.27e6 |    1.26e6 |        1.27e6 |   1.48e1 |   1.26e6 | 1.26e6 |
| sumFoldr      |   2.77e6 | 2.92e6 |    3.58e6 |        3.16e6 |   1.50e1 |   2.79e6 | 2.76e6 |
| sumFuse       |   1.32e5 | 1.32e5 |    1.32e5 |        1.32e5 |   1.59e1 |   1.32e5 | 1.32e5 |
| sumFuseFoldl' |   1.32e5 | 1.32e5 |    1.32e5 |        1.32e5 |   1.68e1 |   1.32e5 | 1.32e5 |
| sumFuseFoldr  |   1.55e6 | 1.55e6 |    1.59e6 |        1.54e6 |   1.70e1 |   1.54e6 | 1.54e6 |
| sumFusePoly   |   1.92e5 | 1.92e5 |    1.92e5 |        1.92e5 |   1.71e1 |   1.92e5 | 1.92e5 |
| sumLambda     |   8.21e5 | 8.26e5 |    8.23e5 |        8.28e5 |   1.52e1 |   8.31e5 | 8.09e5 |
| sumMono       |   7.78e5 | 7.80e5 |    7.82e5 |        7.79e5 |   1.50e1 |   7.83e5 | 7.79e5 |
| sumPoly       |   8.46e5 | 8.41e5 |    8.48e5 |        8.37e5 |   1.45e1 |   8.41e5 | 8.48e5 |
| sumSum        |   7.80e5 | 7.81e5 |    7.77e5 |        7.74e5 |   1.47e1 |   7.79e5 | 7.76e5 |
| sumTail       |   7.24e5 | 7.61e5 |    7.64e5 |        7.29e5 |   1.50e1 |   7.57e5 | 7.23e5 |
| sumTailLazy   |   1.36e6 | 1.37e6 |    1.37e6 |        1.36e6 |   1.53e1 |   1.37e6 | 1.37e6 |
:end:

*** sums

#+begin_src sh :output drawer :exports both
perf-explore -n 1000 -l 1000 --sums
#+end_src

#+RESULTS:
|   | label1        | label2 | results |
|   | ---           | ---    |     --- |
|   | sumAux        | time   | 17700.0 |
|   | sumCata       | time   | 17900.0 |
|   | sumCo         | time   | 22100.0 |
|   | sumCoCase     | time   | 16800.0 |
|   | sumCoGo       | time   | 33600.0 |
|   | sumF          | time   | 17500.0 |
|   | sumFlip       | time   | 27800.0 |
|   | sumFlipLazy   | time   | 27000.0 |
|   | sumFoldr      | time   | 22300.0 |
|   | sumFuse       | time   |  1660.0 |
|   | sumFuseFoldl' | time   |  1390.0 |
|   | sumFuseFoldr  | time   |  3940.0 |
|   | sumFusePoly   | time   |  2140.0 |
|   | sumLambda     | time   | 26000.0 |
|   | sumMono       | time   | 14300.0 |
|   | sumPoly       | time   | 22000.0 |
|   | sumSum        | time   | 14200.0 |
|   | sumTail       | time   | 35600.0 |
|   | sumTailLazy   | time   | 27300.0 |

*** lengths

#+begin_src sh :exports both
perf-explore -n 1000 -l 1000 --lengths
#+end_src

#+RESULTS:
|   | label1           | label2 | results |
|   | ---              | ---    |     --- |
|   | lengthAux        | time   | 20300.0 |
|   | lengthCo         | time   | 19100.0 |
|   | lengthCoCase     | time   | 19700.0 |
|   | lengthF          | time   | 17400.0 |
|   | lengthFMono      | time   | 17000.0 |
|   | lengthFlip       | time   | 23500.0 |
|   | lengthFlipLazy   | time   | 23600.0 |
|   | lengthFoldr      | time   | 18100.0 |
|   | lengthFoldrConst | time   | 18000.0 |
|   | lengthTail       | time   | 29500.0 |
|   | lengthTailLazy   | time   | 24000.0 |

** Gauge

#+begin_src sh :results output :exports both
perf-explore -n 1000 -l 1000 --average --gauge
#+end_src

#+RESULTS:
#+begin_example
sumFuse
benchmarking function ... function                                 time                 583.5 ns

benchmarking function ... function                                 time                 583.5 ns

sum
benchmarking function ... function                                 time                 3.691 μs

benchmarking function ... function                                 time                 3.645 μs

lengthF
benchmarking function ... function                                 time                 1.871 μs

benchmarking function ... function                                 time                 1.874 μs

constFuse
benchmarking function ... function                                 time                 293.0 ns

benchmarking function ... function                                 time                 299.8 ns

mapInc
benchmarking function ... function                                 time                 9.618 ns

benchmarking function ... function                                 time                 10.65 μs

noop
benchmarking function ... function                                 time                 5.254 ns

benchmarking function ... function                                 time                 5.249 ns

#+end_example

#+begin_src sh :results drawer :exports both
perf-explore --examples -n 10000 --averagesecs
#+end_src

#+RESULTS:
:results:
| label1    | label2 | results |
|-----------+--------+---------|
| constFuse | time   | 4.30e-7 |
| lengthF   | time   | 7.24e-6 |
| mapInc    | time   | 8.80e-8 |
| noop      | time   | 3.12e-8 |
| sum       | time   | 5.95e-6 |
| sumFuse   | time   | 1.95e-6 |
:end:

** Space

Data is collected from GHCStats

- allocated_bytes
- gcs
- gcdetails_live_bytes
- max_live_bytes
- max_mem_in_use_bytes

#+begin_src sh :results drawer :exports both
perf-explore -n 10 -l 100000 --space +RTS -T -RTS
#+end_src

#+RESULTS:
:results:
| label1 | label2       | results |
|--------+--------------+---------|
| sum    | MaxMem       |       0 |
| sum    | allocated    |  5.12e6 |
| sum    | gcLiveBytes  |       0 |
| sum    | gcollects    |       0 |
| sum    | maxLiveBytes |       0 |
:end:

*** spacetime

#+begin_src sh :results drawer :exports both
perf-explore -n 10 -l 100000 --spacetime +RTS -T -RTS
#+end_src

#+RESULTS:
:results:
| label1 | label2       | results |
|--------+--------------+---------|
| sum    | MaxMem       |  1.57e5 |
| sum    | allocated    |  7.21e6 |
| sum    | gcLiveBytes  |  1.50e5 |
| sum    | gcollects    |  1.52e5 |
| sum    | maxLiveBytes |  1.56e5 |
| sum    | time         |  1.47e5 |
:end:

** Perf.Degrade

#+begin_src sh :results drawer :exports both
perf-explore -n 1000 -l 1000 --examples --check --record
#+end_src

#+RESULTS:
:results:
| constFuse | time | 1.72e3 | 1.00e3 | improvement |
| lengthF   | time | 2.42e4 | 2.40e4 |                        |
| mapInc    | time | 4.88e2 | 3.56e2 | improvement |
| noop      | time | 4.80e1 | 7.00e1 | degraded    |
| sum       | time | 3.15e4 | 2.72e4 | improvement |
| sumFuse   | time | 1.63e3 | 1.62e3 |                        |
:end:

** Resources

[[https://en.wikipedia.org/wiki/Time_Stamp_Counter][rdtsc]]

** BigO

We could do a regression and minimise the error term, but we know that the largest run contains the most information; we would need to weight the simulations according to some heuristic.

Instead, we:

- estimate the order factor for each possible Order, from N3 to N0, setting the highest n run constant factor to zero,
- pick the order based on lowest absolute error result summed across all the runs,

#+begin_src haskell :results output :exports both
sims = 100
ns = [1,10,100,1000,10000]
ms <- tcurve StatBest sims (\x -> sum [1..x]) ns
ms
(o',res) = estO ns ms
o'
res
#+end_src

#+RESULTS:
:
: >  > [2723.1340382522158,3193.0,8273.0,92495.53333333334,931010.0]
: > Order {factors = [0.0,0.0,0.0,0.0,93.101,0.0,0.0,0.0]}
: [2630.0330382522156,2261.99,-1037.1000000000004,-605.4666666666599,0.0]


#+begin_src haskell
estOrder (\x -> sum [1..x]) 100 [1,10,100,1000,10000]
#+end_src

#+RESULTS:
: Order {factors = [0.0,0.0,0.0,0.0,1.0852114021956238e-2,0.0,0.0,0.0]}


* spacetime debug

#+begin_src haskell :results output
:t toMeasureN 2 ((\x y -> ssToList x <> [fromIntegral y]) <$> space False <*> stepTime)
:t ((\x y -> ssToList x <> [fromIntegral y]) <$> space False <*> stepTime)

#+end_src

#+RESULTS:
: ((\x y -> ssToList x <> [fromIntegral y]) <$> space False <*> stepTime)
:   :: Num a => StepMeasure IO [a]
