resolver: lts-15.6

packages:
  - perf
  - perf-analysis
  - perf-criterion
  # - ../readme-lhs

extra-deps:
  - readme-lhs-0.5.0
  - rdtsc-1.3.0.1
  - tdigest-0.2.1
  - text-format-0.3.2

allow-newer: true
