resolver: lts-14.11

packages:
  - perf
  - perf-analysis
  - perf-criterion

extra-deps:
  - readme-lhs-0.2.2
  - rdtsc-1.3.0.1
  - tdigest-0.2.1
  - text-format-0.3.2
  - pandoc-2.7.3
  - pandoc-types-1.17.6.1

allow-newer: true
