resolver: nightly-2020-06-25

packages:
  - perf
  - perf-examples

extra-deps:
  - git: https://github.com/tonyday567/numhask-space
    commit: 6525f5096525196fe367dabdfe596a7bd0c0aa6c
  - git: https://github.com/tonyday567/numhask
    commit: 37ee8dced120f60a511baa6bb6c7ac382b1e8827
    subdir: numhask-prelude
  - git: https://github.com/tonyday567/numhask
    commit: 37ee8dced120f60a511baa6bb6c7ac382b1e8827
    subdir: numhask
  - git: https://github.com/tonyday567/readme-lhs
    commit: 36b895ee81aad473131e07ef40ba964765362b00
  - rdtsc-1.3.0.1
  - git: https://github.com/jgm/pandoc
    commit: cd3941d34e578f2ebd4dd11484fc26c7afae8a6a
  - hslua-1.1.2
  - jira-wiki-markup-1.3.2
