name: perf
version: '0.4.0.1'
synopsis: Low-level run time measurement. 
description: ! '
  A set of tools to accurately measure time performance of Haskell programs. 
 
  perf aims to be lightweight by having minimal dependencies on standard libraries.

  See the Perf module for an example and full API documentation.
'
category: project
author: Tony Day, Marco Zocca
maintainer: tonyday567@gmail.com
copyright: Tony Day
license: BSD3
github: tonyday567/perf
extra-source-files:
  - stack.yaml
  - CHANGELOG.md
ghc-options:
  - -Wall
  - -Wcompat
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wredundant-constraints
library:
  source-dirs: src
  exposed-modules:
    - Perf
    - Perf.Measure
    - Perf.Cycle
  dependencies:
    - base >=4.7 && <4.12
    - containers
    - deepseq
    - foldl
    - rdtsc
    - text
    - transformers
    - time
tests:
  test:
    main: test.hs
    source-dirs: test
    dependencies:
      - base >=4.7 && <4.12
      - doctest
